[Variables]
; ------------------------------------------------------------- ;
; --------------------------- List1 --------------------------- ;

Clock.Menu.List1.Clock=orologio
Clock.Menu.List1.Extras=extra
Clock.Menu.List1.SkinSettings=impostazioni skin

; ------------------------------------------------------------- ;
; --------------------------- List2 --------------------------- ;

Clock.Menu.List2.Shape=forma
Clock.Menu.List2.Text=test
Clock.Menu.List2.Style=stile
Clock.Menu.List2.Color=colore
Clock.Menu.List2.Format=formato
Clock.Menu.List2.Language=Lingua
Clock.Menu.List2.Manage=Gestisci
Clock.Menu.List2.Edit=Modifica
Clock.Menu.List2.Unload=Smonta

; ------------------------------------------------------------- ;
; --------------------------- List3 --------------------------- ;

Clock.Menu.List3.ZPos=Posizione

; ------------------------------------------------------------- ;
; --------------------------- Items --------------------------- ;

Clock.Menu.Item.Widtht=Larghezza
Clock.Menu.Item.Heightt=Altezza
Clock.Menu.Item.Radiust=Raggio

; ------------------------------------------------------------- ;

Clock.Menu.Item.Paddingt=Riempimento
Clock.Menu.Item.Glow=Luminescenza

; ------------------------------------------------------------- ;

Clock.Menu.Item.Background=Sfondo
Clock.Menu.Item.Acrylic=Acrilico
Clock.Menu.Item.Corner=Angoli Arrotondati
Clock.Menu.Item.Border=Bordo

; ------------------------------------------------------------- ;

Clock.Menu.Item.Latte=Latte
Clock.Menu.Item.Frappe=Frappe
Clock.Menu.Item.Macchiato=Macchiato
Clock.Menu.Item.Mocha=Mocha
Clock.Menu.Item.Custom=Personalizzato
Clock.Menu.Item.CustomColor=Personalizza Colori

; ------------------------------------------------------------- ;

Clock.Menu.Item.Hour=12 Ore 
Clock.Menu.Item.Second=Secondi
Clock.Menu.Item.Indicator=AM/PM
Clock.Menu.Item.Date=Data
Clock.Menu.Item.CustomDate=Personalizza Data

; ------------------------------------------------------------- ;

Clock.Menu.Item.Screensaver=Screensaver
Clock.Menu.Item.OpenKeyT=Modalità apertura
Clock.Menu.Item.QuitKeyT=Modalità chiusura

; ------------------------------------------------------------- ;

Clock.Menu.Item.en=Inglese
Clock.Menu.Item.es=Spagnolo
Clock.Menu.Item.it=Italiano
Clock.Menu.Item.custom2=Personalizzata
Clock.Menu.Item.customLanguage=Personalizza Lingua

; ------------------------------------------------------------- ;

Clock.Menu.Item.StayTopMost=Sempre In Primo Piano
Clock.Menu.Item.TopMost=In Primo Piano
Clock.Menu.Item.Normal=Normale
Clock.Menu.Item.Bottom=In Basso
Clock.Menu.Item.OnDesktop=Sul Desktop

; ------------------------------------------------------------- ;
Clock.Menu.Item.ClickThrough=Clicca Attraverso
Clock.Menu.Item.Draggable=Trascinabile
Clock.Menu.Item.KeepOnScreen=Tieni Sullo Schermo
Clock.Menu.Item.SnapEdges=Aggancia Ai Bordi

; ------------------------------------------------------------- ;